pub mod text;
pub mod divider;
pub mod icon;
pub mod button;
pub mod image;
pub mod switch;
pub mod check_box;
pub mod slider;
pub mod input;
pub mod card;
pub mod avatar;
pub mod badge;
pub mod chip;
pub mod header;
pub mod list_item;
pub mod tab;
pub mod search_bar;
pub mod linear_progress;
pub mod rating;
pub mod fab;
pub mod tooltip;
pub mod overlay;
pub mod dialog;
pub mod tile;
pub mod pricing_card;
pub mod skeleton;
pub mod speed_dial;
pub mod social_icon;
pub mod markdown;
pub mod svg;
pub mod fade_view;
pub mod blur_view;
pub mod fading_bar;
pub mod curved_label;
pub mod staggered_grid;

use makepad_widgets::*;

pub fn live_design(cx: &mut Cx) {
    self::text::live_design(cx);
    self::divider::live_design(cx);
    self::icon::live_design(cx);
    self::button::live_design(cx);
    self::image::live_design(cx);
    self::switch::live_design(cx);
    self::check_box::live_design(cx);
    self::slider::live_design(cx);
    self::input::live_design(cx);
    self::card::live_design(cx);
    self::avatar::live_design(cx);
    self::badge::live_design(cx);
    self::chip::live_design(cx);
    self::header::live_design(cx);
    self::list_item::live_design(cx);
    self::tab::live_design(cx);
    self::search_bar::live_design(cx);
    self::linear_progress::live_design(cx);
    self::rating::live_design(cx);
    self::fab::live_design(cx);
    self::tooltip::live_design(cx);
    self::overlay::live_design(cx);
    self::dialog::live_design(cx);
    self::tile::live_design(cx);
    self::pricing_card::live_design(cx);
    self::skeleton::live_design(cx);
    self::speed_dial::live_design(cx);
    self::social_icon::live_design(cx);
    self::markdown::live_design(cx);
    self::svg::live_design(cx);
    self::fade_view::live_design(cx);
    self::blur_view::live_design(cx);
    self::fading_bar::live_design(cx);
    self::curved_label::live_design(cx);
    self::staggered_grid::live_design(cx);
}
