pub mod text_page;
pub mod divider_page;
pub mod icon_page;
pub mod button_page;
pub mod image_page;
pub mod switch_page;
pub mod check_box_page;
pub mod slider_page;
pub mod input_page;
pub mod card_page;
pub mod avatar_page;
pub mod badge_page;
pub mod chip_page;
pub mod header_page;
pub mod list_item_page;
pub mod tab_page;
pub mod search_bar_page;
pub mod linear_progress_page;
pub mod rating_page;
pub mod fab_page;
pub mod tooltip_page;
pub mod overlay_page;
pub mod dialog_page;
pub mod tile_page;
pub mod pricing_card_page;
pub mod skeleton_page;
pub mod speed_dial_page;
pub mod social_icon_page;

use makepad_widgets::*;

pub fn live_design(cx: &mut Cx) {
    self::text_page::live_design(cx);
    self::divider_page::live_design(cx);
    self::icon_page::live_design(cx);
    self::button_page::live_design(cx);
    self::image_page::live_design(cx);
    self::switch_page::live_design(cx);
    self::check_box_page::live_design(cx);
    self::slider_page::live_design(cx);
    self::input_page::live_design(cx);
    self::card_page::live_design(cx);
    self::avatar_page::live_design(cx);
    self::badge_page::live_design(cx);
    self::chip_page::live_design(cx);
    self::header_page::live_design(cx);
    self::list_item_page::live_design(cx);
    self::tab_page::live_design(cx);
    self::search_bar_page::live_design(cx);
    self::linear_progress_page::live_design(cx);
    self::rating_page::live_design(cx);
    self::fab_page::live_design(cx);
    self::tooltip_page::live_design(cx);
    self::overlay_page::live_design(cx);
    self::dialog_page::live_design(cx);
    self::tile_page::live_design(cx);
    self::pricing_card_page::live_design(cx);
    self::skeleton_page::live_design(cx);
    self::speed_dial_page::live_design(cx);
    self::social_icon_page::live_design(cx);
}
